name: "Build kernels"

env:
  OUT_DIR: "${{ github.workspace }}/out"

on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    name: "Build kernel"
    runs-on: ubuntu-22.04
    env:
      WORKSPACE: ${{ github.workspace }}
      KERNEL_NAME: Nethunter_kernel_samsung_dm3q
      KERNEL_REPO: "https://github.com/MK-986123/Nethunter_kernel_samsung_dm3q.git"
      KERNEL_BRANCH: "WIP"
      KERNEL_DEVICE: "samsung_dm3q"
      DEFCONFIG_NAME: "vendor/kalama-gki_defconfig"
      withKernelSU: false
      useAnykernel: true
      release: true
    steps:
      - name: "Get build date"
        run: echo "builddate=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: "Install prerequisites"
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc flex bison libssl-dev curl git zip ftp gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi lftp zstd wget libfl-dev python2 python3 libarchive-tools libelf-dev

      - name: "Prepare output directory"
        run: mkdir -p "${{ env.OUT_DIR }}"

      - name: "Setup Anykernel3"
        run: |
          git clone --recursive --depth=1 -j"$(nproc)" --branch master https://github.com/osm0sis/AnyKernel3 AnyKernel3
          echo "Setup Anykernel3 => (https://github.com/osm0sis/AnyKernel3)"

      - name: "Clone kernel source"
        run: |
          git clone --recursive --depth=1 -j"$(nproc)" --branch $KERNEL_BRANCH $KERNEL_REPO $KERNEL_NAME
          echo "Clone kernel source => ($KERNEL_REPO)"

      - name: "Get toolchains"
        run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang.git toolchains/proton-clang
          echo "Toolchains setup complete."

      - name: "Set build args"
        id: generate-args
        run: |
          echo "THREAD=$(nproc --all)" >> $GITHUB_ENV
          echo "arch=arm64" >> $GITHUB_ENV
          echo "CC=toolchains/proton-clang/bin/clang" >> $GITHUB_ENV
          echo "args=-j$(nproc --all) O=${{ env.OUT_DIR }} ARCH=arm64 CC=${{ github.workspace }}/toolchains/proton-clang/bin/clang" >> $GITHUB_ENV

      - name: "Update KernelSU"
        working-directory: ${{ env.KERNEL_NAME }}
        if: ${{ env.withKernelSU == 'true' }}
        run: |
          if [ -d "./KernelSU" ]; then
            rm -rf "./KernelSU"
          fi
          if [ -d "./drivers/kernelsu" ]; then
            rm -rf "./drivers/kernelsu"
          fi
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
          echo -e "CONFIG_KPROBES=y" >> arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
          echo -e "CONFIG_HAVE_KPROBES=y" >> arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
          echo -e "CONFIG_KPROBE_EVENTS=y" >> arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
          cat arch/arm64/configs/${{ env.DEFCONFIG_NAME }}

      - name: "Make defconfig"
        working-directory: ${{ env.KERNEL_NAME }}
        run: |
          make $args $DEFCONFIG_NAME

      - name: "Build kernel"
        working-directory: ${{ env.KERNEL_NAME }}
        run: |
          make Image $args

      - name: "Upload Image"
        uses: actions/upload-artifact@v4
        with:
          name: Image-${{ env.KERNEL_DEVICE }}-${{ env.KERNEL_NAME }}-${{ env.builddate }}
          path: ${{ env.OUT_DIR }}/arch/arm64/boot/Image
          retention-days: 20
        continue-on-error: true

      - name: "Upload Image.gz"
        uses: actions/upload-artifact@v4
        with:
          name: Image.gz-${{ env.KERNEL_DEVICE }}-${{ env.KERNEL_NAME }}-${{ env.builddate }}
          path: ${{ env.OUT_DIR }}/arch/arm64/boot/Image.gz
          retention-days: 7
        continue-on-error: true

      - name: "Pack AnyKernel3.zip"
        if: ${{ env.useAnykernel == 'true' }}
        env:
          anykernel: "${{ env.WORKSPACE }}/${{ env.KERNEL_DEVICE }}-${{ env.KERNEL_NAME }}_${{ env.builddate }}"
        run: |
          ls -al
          if [ -e "${{ env.OUT_DIR }}/arch/arm64/boot/Image.gz-dtb" ]; then
            cp -f ${{ env.OUT_DIR }}/arch/arm64/boot/Image.gz-dtb ./AnyKernel3/
          fi
          cd AnyKernel3/
          zip -q -r "${{ env.anykernel }}.zip" *

      - name: "Upload AnyKernel3 image"
        uses: actions/upload-artifact@v4
        if: ${{ env.useAnykernel == 'true' }}
        with:
          name: "${{ env.KERNEL_DEVICE }}-${{ env.KERNEL_NAME }}_${{ env.builddate }}"
          path: AnyKernel3/*

      - name: "Create GitHub Release"
        continue-on-error: true
        uses: softprops/action-gh-release@v1
        if: ${{ env.useAnykernel == 'true' && env.release == 'true' }}
        with:
          tag_name: v${{ env.builddate }}.${{ github.run_number }}
          files: "${{ env.WORKSPACE }}/${{ env.KERNEL_DEVICE }}-${{ env.KERNEL_NAME }}_${{ env.builddate }}.zip"
          generate_release_notes: true
